version: 1
dataset_version: db-gsm8-v1.0

train:
  - 36d1f7f5-b3a5-448d-b404-9fa437eae18d
  - c7a35af2-c13b-4e49-9c0e-a4c74935d868
  - ca3ea91b-6b84-401c-8cdc-ca225a017bac
  - 8665564d-bb47-459b-ae9e-b3ec20d55842
  - 1a69dfdd-2db9-439b-9f23-086b738fa9a0
  - 8badfc54-9003-4bff-bbd9-4d682474f7f9
  - 7406b15d-82b4-433d-b581-56c723a3d17e
  - 212f0387-f74e-475a-813d-370c6f22d2f7
  - e91a7ba2-2788-4cdc-8d2a-7f87c6dd4681
  - 18e3d181-4132-4998-bee1-02a8e7b66ca3
  - f448ddca-c9c1-4f2a-a69a-ca6985159848
  - dbb98b1b-14ac-4cb3-a463-0aece630d867
  - bbe6ae6a-807b-4261-bd50-ef59c772ff82
  - 7676141c-c926-4a95-9c61-62e36fca5d77
  - f7daab46-f78d-48fc-8885-a58fd1e2e1fd
  - 05c21fdc-0834-4fae-9d6f-3c3ab59952e3
  - 119f47b8-437e-4260-8c2a-29d0cbe0a0d4
  - cd8c8fed-6a4d-4548-95ea-9fb700882646
  - 5ed60909-6523-428a-9f97-4d5845615945
  - 9076b1e1-93c3-404a-a232-8d2bbb3c44b4
  - cad34d7c-c8a0-4497-bf85-c450041e4908
  - dab557ae-3434-4aec-b74c-8ef2e65dced1
  - 2da92b6c-b564-4133-b7c1-6d348cde9195
  - 27f4da0c-de16-4a03-b9af-f9f0089cf512
  - 3478fba7-1636-4f8d-85bc-5478abff36c2
  - d4234e6f-dfac-4ac1-901a-ffc4da9b32a1
  - 58d147c3-1d91-47e8-ac6c-7ee4c8f07ac9
  - ad923bdc-31ac-4ab4-b528-2368c5b6b04e
  - de0bdd07-9961-424c-abd6-4634339300c4

val:
  - 9fe8e1d4-e08e-4f88-b42e-42bf777dbbe7
  - 786a6bd6-43b8-4dbe-880a-5c2c8c7cd46e
  - 49028b39-2448-4b25-98df-fb23c92e194d
  - 50b953c3-96ab-4bb6-8a72-e194dd5cfcec
  - 913e6cf7-7c12-48a1-a390-3e6a79761ac7
  - 393c5cb2-4760-42a2-a415-43d678534858

test:
  - 8cff354a-cca5-47ed-83fa-a3fa7d31588a
  - bba6a63a-55cd-411b-b5be-e5de4834a2f1
  - ea464363-6ac8-43cb-a3a9-4ac2dd234283
  - e11a7dfc-032d-4cdd-a015-33ec19aada02
  - e19cf12b-24ed-4227-a51c-1f35eb1f9433
