version: 1
dataset_version: db-jpntaxi-v2.0

train:
  - e6d0237c-274c-4872-acc9-dc7ea2b77943
  - 80b37b8c-ae9d-4641-a921-0b0c2012eee8
  - 4d50abff-427f-4fa8-9c04-99dc13a3a836
  - aa2626e5-3ecb-47a5-9584-6e022e813bfc
  - a81a5d0a-e7c3-4ace-a331-94656a84214f
  - dbdee5c4-ec50-4ebb-b18c-e675291b1c81
  - 80181354-07ac-46ba-9bab-3cb8db01dadd
  - d6264c3e-8b3b-42e9-8993-e5c8a951611c
  - 8706a30e-33da-4205-8128-18add3cd2d45
  - d59a9b59-e41b-4f05-a67f-634851aa82de
  - 4ea652e7-76d5-4240-adb5-9d4ecac25eae
  - 6d038cea-92df-43a5-a805-febf74086a57
  - 39f68b13-c9fa-47d6-b54c-9630ae0348fd
  - 90d255b9-4977-4129-848c-e65c0bad9d6d
  - d0c20918-dc89-4b30-b657-ceeb2103c826
  - 7a095434-2916-4533-9c1b-01965fabe9cd
  - 30cb86e3-985e-4c29-be6a-9e1b21e2ec44
  - 810e9575-5042-4bee-8188-6c4d64b0a0d4
  - f258e460-8a03-4b49-b70c-cd4e34f97226
  - 2986a406-0f06-4c58-be03-f1421bd68e07
  - c57c04d7-8984-4e3b-97af-0edfaf2e9e35
  - e6b5f181-4529-45f6-81b0-26e6c069155f
  - 1c95e157-f097-4c6a-a6c9-71de3b3ca917
  - 68b2c916-a0ee-4545-927b-fcedeac303df
  - 68af08a6-4584-4a82-8063-3e08221d1f84
  - 1f286039-2772-4d05-86cf-a19db254832a
  - 16a1e49a-6eff-4882-8441-94efcf89d073
  - 7371cec9-4487-41eb-9e2a-302c72ee256a
  - 42c1ff8c-e960-4514-8e66-31897758dae8
  - 16b574ba-b328-4c4c-b432-031224df2a52
  - 1980f07f-c051-440c-9085-ab3d7012ef80
  - b3f4ba86-d703-4f8c-bc40-2a6ea4a0ef31
  - cfb8781f-37b2-4a18-8b6f-b691986e4b10
  - 2d4fb9c4-b587-42af-9b63-9cbe6dc5d5db
  - 78c396f3-4428-4dd2-a00f-01f7564d9ee5
  - 5a8e0972-f68d-4274-9544-ef349edd8f1e
  - d1ad49cd-12c2-4d28-828f-533e35abb18a
  - 913ce874-c70e-45ea-bc26-0d50730636cc
  - d09b1786-b76b-4b89-be75-dd21b6ac9cf9
  - 5e640323-de15-4d7c-88d9-4d18647c6b35
  - 207ea2e7-8ae2-40da-b898-e8777c1e40c2
  - 80516045-2c1f-4170-825a-862e01c8b56a
  - 6640582e-5d08-4e06-8ea2-d764b443a3c6
  - f20790a5-b067-421c-b372-f71d1e591974
  - 4ffdc4d7-2cd2-4606-a255-a811a3b2151c
  - 657038d4-41bc-4a61-a9fd-2d6d4f27663c
  - 32feb169-5285-408d-8fc0-6ae9382dd60c
  - 7c101a9a-b401-447c-bfd1-2cc4b73bab9d
  - 7881b896-46dd-46ab-8a8d-aab740a28a95
  - 513da928-ae1c-4629-85b5-a9bf34169a0a
  - 37f08024-b7cf-44a1-a1a7-d02b91098ad7
  - e8c58365-3d17-4e7f-ab19-fbd71d84fe10
  - 858b99c5-d5d2-4f3b-a9c1-fee69377b0de
  - 0171a378-bf91-420e-9206-d047f6d1139a
  - ca346afb-ea1a-4c5c-8117-544bd9ff6aca
  - 7bf7441c-efb7-45fa-acf3-361f54b729a8
  - 48cdbaee-8c7b-40f8-b00d-fa20283c8614
  - 4df4be60-bf6c-4144-a4c2-db3bde0ffed3
  - d20b53bf-8b4e-4040-9d2c-6df22120177a
  - 1e34553e-0c1f-4784-b11f-42b02fa363d0
  - e9f6ab6b-f779-4dd5-9fc5-14e5fabd265c
  - d8099a11-52e3-48d4-893b-795df0ed5d15
  - e41caf64-aea7-4188-b1ff-6a79d7a21eed
  - 6c1669b0-2010-4df8-93e1-d771af4f163a
  - 44bdcf66-c35e-430f-af34-70c503ecf62c
  - ad24fed9-b38e-4c69-863a-e93b124e1f75
  - 75140d29-80da-4826-9efd-e8410bd460a7
  - bdd6568a-7d41-45c4-8b8f-47569fd61866
  - 6de46588-b4d8-4497-95c5-a0abe679792b
  - fbf4355a-74d1-4939-932e-9d7de71dcb03
  - 40efb087-083c-48ec-885a-14991598b551
  - 120f402c-9c58-426f-ab6f-d13e09bf30b4
  - 53d20443-cfaf-4199-be9a-e941f2f47e6f
  - ed96b707-e7f4-4a71-9e6b-571ffd56c4c4
  - 753a2a13-9cec-474d-afee-48558dd8ff01
  - b29a8788-f01a-4a21-a03f-586fece90175
  - 133ac82f-0dbe-4ed0-a566-e2506fec4094
  - 63c5a18a-bbfc-4816-9e79-203c6492a165
  - 8034d7b5-df2f-442e-a7be-da984c6e0c2e
  - dd759377-4ff7-49c5-9d42-5b1c30eba18b

val:
  - 3013c354-2492-447b-88ce-70ec0438f494
  - c8cf2fe3-9097-4f8d-8984-e99c4ddd0ced
  - a1f10b82-6f10-47ab-a253-a12a2f131929
  - 3ebf5eef-940f-4877-a093-a1ec933505e8
  - 5fa608b9-5321-4cac-8f21-d2b1e215c9aa
  - 198435d1-5648-421c-a284-35b26a52136e
  - 96200480-ae59-44cb-9e4e-dd9021e250e8

test:
  - 13351af0-41cb-4a96-9553-aeb919efb46e
  - 9e973a55-3f70-48e0-8b37-a68b66a99686
  - 54a6cc24-ec9d-47f5-b2bf-813d0da9bf47
  - 5f1c6a02-9193-487a-8ba8-74f4d3f4d609
  - a7ce24a6-a506-47be-8254-884365ca52f3
  - 9cbc58ea-1498-49dd-8fc5-e61c2ec26187
  - cf835959-ece5-40da-b685-71425747f7af
  - a7d001ce-6591-4597-8ce3-6f28a49dcbe3
  - 92403ff0-81ad-49cc-94c5-f1cc4581ab93
  - 0338521f-321a-4a9a-9c52-480f1ae1131a
