version: 1
dataset_version: db-j6-v2.0

train:
  - f159d562-f87b-4dab-a993-1884b2c7042e
  - d85c57df-f937-4360-96e2-3eb6a9ea5b7f
  - 7b9a0db5-6fd2-46d8-a9fb-33e90437bae8
  - be882f53-0e90-438a-8da3-caed58d4348e
  - cd502d8c-176a-43f9-9a10-b3db93dbf445
  - b68bee61-60d6-4131-aa29-953487c27588
  - 73c03af6-f371-4b74-a46f-06b434c6a59b
  - d804cad5-b094-478f-92ca-77f27b640acb
  - 7f01452e-3473-4daf-97a1-3b5c3d56c69d
  - d20e21da-0247-4ae4-a1ee-c9a27dca9fb6
  - 9d8b8b20-32ef-4d48-a058-90f450a670b3
  - 1c0ecf5c-bb5c-4b77-9570-4e98fdbfd8b9
  - 968904f8-4991-4772-9639-c7226b6731c6
  - 51d2931e-8385-460d-955d-a741dd5cc731
  - 67feb427-4b9c-4356-b65f-a7c4263840d4
  - a4639c85-ebba-4d91-8205-c701282e8df0
  - c29ccf6d-756a-4b71-820e-3dcc1901534b
  - 1cea1e2a-99d1-49a3-a4bd-eb5486f52aff
  - 048638e2-64f4-4a88-96ea-f23223f9f461
  - 7315e6c4-5566-483a-a020-3d375435af7c
  - a89e049a-d4e9-4232-ad75-915837cb8aba
  - b13cfb2a-f9b3-4cbd-8812-bd19fce03cde
  - cbef2f5c-2331-4e46-822c-408d8cb74d10
  - b8ea501d-031e-4754-885c-6198c754e89c
  - a5d4a852-4f7c-4143-836b-b5e99d442622
  - b406c4ad-e182-435c-b88d-b53641acfff6
  - b309d001-b27c-4917-9040-eb261c14231f
  - c789738c-3c50-4226-a1c4-7136a8bb6890
  - cfd9fc26-31d1-42cc-a77c-31397897a60d
  - f254eb62-d808-4495-8a83-b52909d0c2ae
  - 00479515-94a3-4a51-a8c2-4576a90ebadd
  - c584f223-2b56-4ea8-a1c9-4f5ed1f9880d
  - 3db3d34e-b5c1-44bd-b308-ecfac4c5ad05
  - eb9bace1-0afa-489d-ad53-3e6791cb802d
  - b003b42c-5f25-4b08-abf3-bd06fbf84bc0
  - 9ab4eb3e-d766-4759-9d1f-b5f8eb3503fe
  - 474e258e-bd12-4d9a-b5c0-dfdd4eb18ea8
  - 2488f69a-ae91-4e6b-a33d-74718a703a47
  - 6ca96178-f7b2-4315-ae4c-15d10600964b
  - 2c43ad73-1978-4c9b-bfb9-e1453588827a
  - 0d237951-1901-4d24-a7d4-21c672ba704a
  - 507b1e5c-918e-4568-a134-fd34d477f356
  - 579a3607-4907-4ece-a1d5-e963e057865c
  - 8b6a1124-fb17-4473-96a6-10bc24d2822f
  - dc9e5723-4f6d-4b80-a1f7-3ab6aed53540
  - 62a21678-a3af-47c1-9564-6fb15cbd216b
  - 5b325065-d00d-4fac-bf02-b869652e8f6e
  - a25034bb-2f3e-4b5a-8372-668ad92058fd
  - 40d05165-2c8d-4dbc-92b6-a8b4a62c444a
  - c2709364-8b8c-4744-9fdf-98356e1aa7e1
  - a644b13f-4e34-46cc-9ab0-26909271729a
  - fa05eaf7-1b9d-4d3e-849d-c64c2a6115df
  - ab0fff1c-bc31-4ef6-a87b-2a12351472ac
  - a8183f3d-394f-467b-b60b-34a1c9c6ae75
  - 925a82e3-1ed8-451d-94eb-b15c49b2ddc6
  - bdbb795b-f79f-41c8-b635-f7de7e2558dd
  - 23690bc0-2536-4d1a-82f4-e3a1851ecd94
  - b20716e7-03a1-435d-a5b9-085b91e920d4
  - a2f082c9-2428-472f-ae3c-f96887a113f2
  - 4b82b895-a571-41a2-b08e-cc1ff3175f41
  - 4ff935ea-9084-4de3-9215-3b0b9e944603
  - 55a0c6a6-472d-4e59-89a6-2db38775fcaa
  - a9e6e647-7607-4f46-99d0-b8d2e2e1b607
  - 73d5f258-ec03-400e-8021-42476a18f7da
  - 66a36901-3ea3-4083-a252-090a4f198b2d
  - a3b397bb-3953-41d2-be7f-aa32baad4856
  - 0157a21c-5293-456a-9898-102a3da8820a
  - 83caf70f-e2a4-41ee-9b65-ef2f5f269c83
  - 758923ac-2881-48b6-9bfb-44d71e9aa772
  - 75d4a6d0-01b3-4ce2-9d67-12f9c5da8c8e
  - b858380e-0a85-46f0-bc32-fe974ba4653f
  - 07d02291-f227-49d1-9246-e5edce83c280
  - 9da9cee6-2468-4696-9596-8b76e85cb93f
  - b2da086f-a922-4602-aa9f-65c975298e1a

val: []
test: []
