version: 1
dataset_version: db-jpntaxigen2-v1.0
train:
  - dc90e149-1170-42ab-a075-3ea75b11e9e2   0
  - 6ec8d740-8771-4b5b-ae0a-d7ecb1993c1a   0
  - c7d9be5f-05b5-4de7-9f85-ac5a91a5d965   0
  - bc4dc4b3-f60c-4cf6-bc68-76988263511d   0
  - 64c2e637-d170-4e03-bf8d-3d3c58996b8b   0
  - 0bc6f987-fb64-4a76-9df3-bb8629bd7115   0
  - 5831cf18-3b49-45f8-b37e-7b50e4048f5c   0
  - 016241c2-37b4-4126-8221-68da4dcc4e13   0
  - ccec1eb7-f0e6-4a18-ba4e-d3d9b995b598   0
  - e3d3e209-8ac5-4793-a5cc-fe3439b003a8   0
  - 54819912-f0e3-49ac-974e-9f7dc3a2042d   0
  - 5e8d07d9-89a4-43db-b725-f78936e2a9b2   0
  - b91323d7-1e85-4348-b5ca-bf2d0344f580   0
  - 66a67e86-b8e1-436b-b3e6-f08d254192b4   0
  - 6730382b-be53-4b5a-9e08-93bffefa0527   0
  - e4a1e255-7eb2-4f72-8174-f8833106d49e   0
  - 701b7a49-8580-41d2-b9f7-353dc150ba3f   0
  - ad123a1d-bd5d-4838-bf03-8fa85deaa403   0
  - 2bb81162-b5fa-439f-a660-fc1e4250eda3   0
  - fd5ce146-77d3-40d5-a508-1ae39af879bb   0
  - bcb16d27-8466-49fa-a06a-5faa09a7d71d   0
  - 5c1edb84-7c4f-47c9-b61d-166f5afb8d3b   0
  - 3ff13b6c-c485-4d86-be7d-01eee741c316   0
  - 668f67ae-fd90-4656-914e-eda52688f659   0
  - e0f4f52b-3ab0-490a-979b-9e066b20b1c1   0
  - 433a2328-a5a6-4790-87d3-59e930ac7020   0
  - b5f640d7-6e5f-4007-8438-f29a176e8050   0
  - 65a0e036-acd2-499d-825c-a8e56ebadd19   0
  - d5ffa069-6a24-4ea5-81ff-f6e876aeb5ee   0
  - 68b7f4f0-85a3-4c91-aaf2-acc0c5b91ef3   0
  - da6909fa-ae15-464e-b36e-8a46cebd9dde   0
  - b4a3b3f9-f44a-4468-a2ee-c938c711641f   0
  - da79a547-7639-4129-8611-9b3973caa6b1   0
  - 71bf885e-9272-4c48-a69d-320c74111990   0
  - 4623ae11-afbe-409c-95e8-8a289eeb9c63   0
  - 0c2750b8-0d42-4a66-b923-f099b1e0b9f2   0
  - 78b45197-a587-4ada-9d40-1f50758d0e39   0
  - 66bf1186-8cf0-4653-9413-32ef5101947b   0
  - a21d5c78-be0f-4427-ac91-95030d9a9865   0
  - 4c860b9a-dfad-4bbd-b29c-93925cdd8920   0
  - acc79ac6-c799-4644-b84a-41b3b0443310   0
  - 6b554536-c843-427c-8f15-e8f27851b475   0
  - 334f143b-b492-4696-baf3-b3a4c45308b5   0
  - 3475bdb9-a855-4851-9c88-62f9050f3882   0
  - 8f1a914e-b040-4618-8259-51c003b79e35   0
  - ff4b5d47-87a6-4ab6-8fe3-862f824f51a7   0
  - e63f7182-d245-43f0-a270-7c36df81e262   0
  - 64a6c261-428b-433d-adb9-f8d99a4e5d63   0
  - dbc2d47d-3682-4b3a-9362-1728385e5eba   0
  - d0d77abd-ad38-4d9a-8235-67685fa9dc78   0
  - 03f5e2df-0eba-4ce3-8542-fbdf19e38c64   0
  - 461d28b6-42e1-402c-a371-49677a40ad0b   0
  - 1c3601e6-6381-4601-9ae4-d0ea11c2e778   0
  - 656812a4-d194-4c9d-92ee-67f2cd02c2bb   0
  - bd5e4d58-4e91-4e39-8442-a0ba21f678a0   0
  - 3c6175b9-a286-460c-a345-5f1e22377d85   0
  - a6be5a62-84ca-4211-900e-c87904646509   0
  - aa6ca30c-4223-4110-b287-30681a2cadd7   0
  - d7baedbe-7926-4a50-a75f-987f7de30ed6   0
  - c5f2d1d3-6451-4404-8431-a2f2ec88f535   0
  - 45f89794-4207-41ef-a9b9-35fc7f5bcd89   0
  - edd0cf21-3d85-40d0-81d6-d6078fec40f9   0
  - f1429820-bf89-4512-8ae6-17facaef6c10   0
  - 8c555e9a-a6b8-4b79-a4c7-06c5d06de1cf   0
  - ac00a455-3c9a-46ac-97a8-276b42a4ddda   0
  - 4ac1747c-7d89-46da-93d7-63110a7d2c73   0
  - 05d81470-a1fd-479d-8f4d-d7545bc98c7e   0
  - ea18f78e-4d3f-47e6-be10-66900027c0a4   0
  - def7bab8-9f52-42e9-8b9f-88b73023b303   0
  - 7a9d8301-2c6f-4790-9c9f-0582ca519104   0
  - 8521e5e9-4e73-40d7-931a-1786a6f4c7c9   0
  - ca6e7de2-feba-432e-b35d-d33c3230e256   0
  - 9c366c65-857a-4800-8b94-df10063f6981   0
  - f5391fdb-fbb1-4d2c-bfbf-3bbe7ddda06e   0
  - b15e584e-48cd-46d4-8c12-91e6cef51d9a   0
  - 22f12f6a-50c8-4270-a928-619a7a7a2ff7   0
  - ec5c2e75-1fea-4fb9-99ef-7389adc16e54   0
  - 26c7b775-37f9-4f00-8f3b-eefa65c0e98d   0
  - dabbb50c-7e79-4b50-919b-93a512a4eb66   0
  - 145a9d6f-28a9-4627-9747-492efb9c5805   0
  - 89e0a801-659f-4a56-b198-0e3343c19ed6   0
  - 05f7a0c2-c6d6-43fe-b716-b43368f851b9   0
  - fd51a808-b5b6-4c71-9e31-29ae48a00807   0
  - 6210d656-e2e1-4900-a918-ff2aafbacc0b   0
  - 5196790d-8225-4ebe-bd2f-97b2fdb20ba6   0
  - 078df860-171e-45ae-8e4a-2ccb6d7d5f37   0
  - 5d719887-49cc-409b-b36c-e9b56af0a2f5   0
  - 5c822184-9929-47aa-a3b2-82ca902e510a   0
  - e7fa3d35-35fa-4419-b005-0165504767ee   0
  - 455b3808-360c-42ad-a3db-984c30707d6c   0
  - 967efa82-2042-49a1-8a79-99c52b51759d   0
  - ba840de9-702d-4764-8cc2-bdcf15c75769   0
  - 8adcd7e6-7063-402c-b960-abbc0f3729a2   0
  - 305379f3-ae5d-4f33-94a5-3f804390915c   0
  - a44296ac-a5f1-4e13-9355-6b3ddd0558c0   0
  - d9d1cf0f-af3e-4927-9ecb-1c381c7f9421   0
  - cb90b9ac-b4a9-491c-aa3a-3b1c5a4dacc5   0
  - 864b56dd-2d40-4cf4-9696-345c41c350d0   0
  - c24f0655-02b0-4797-8536-b9dc3261b7dd   0
  - 1335dad6-7bce-4d42-b330-247a2c3a8007   0
  - ffbe71ef-ec25-4f91-9764-133cbe1eda23   0
  - 936d3a7f-cedb-4049-8431-40c86117e23a   0
  - 0f2b302a-7309-47f4-8855-00d1284b7a32   0
  - 167ef35e-2da7-4b91-a42a-a0b89b9d39c9   0
  - a7179480-5f72-43b0-99aa-9d8f971522d9   0
  - df18806b-0658-49f3-b78d-6407bcdcb264   0
  - eff003dd-4d2f-4ab5-83d4-1d525a0a2ae1   0
  - 5643836b-7fed-4cff-9a9e-fd87fbd6eee6   0
  - ff18a8e5-cbf6-48e1-9ed6-c2476e990797   0
  - 00284451-6235-419a-8367-9f998b704cf6   0
  - 61f85fbe-0e52-4329-b3bb-422611c1a803   0
  - db67f17c-98b8-4426-9690-1db1235a0e97   0
  - 1d88ac05-c0f0-4d8a-a94a-3e7a51430203   0
  - 1808a511-3880-43b8-b146-10179d66325f   0
  - 4747b931-32ef-442d-9bb3-4ea020d16f41   0
  - 731897ca-75c8-468a-9452-e50bc2aa7003   0
  - 764ee713-cb00-457e-9159-e6de79355034   0
  - fbe03390-b16f-4aca-8e42-7b5052ecd25c   0
  - d51b4e3d-dd5c-4a65-9465-e081c4a859ae   0
  - 97dd92c0-c5b0-438d-acef-c78d5f601313   0
  - 694080cc-857f-46f6-818f-03cc8acb817b   0
  - 7be9b245-9168-4e49-965f-40dae9174909   0
  - b3f28249-7bec-44f7-bf4c-310a39834219   0
  - 1b4a3874-8bbd-4fb3-a96a-53fcb4122092   0
  - cdacb0eb-f72c-40d7-820c-1814cd6b4e2a   0
  - 27e012e9-d326-4945-b9c1-985ae4a5ca71   0
  - 30e2ffc4-b994-4f29-86a9-31a0eee65add   0
  - b72ed0bb-85d5-4da0-ac74-eb6fbd86fe57   0
  - 092810e7-0174-44a2-80e8-9e79cafb3af5   0
  - cb6a216f-d357-4969-8ca3-89e6f9a4fe30   0
  - c86f447f-65d7-4d98-a470-428cad029b3b   0
  - 59f69d5d-32c6-4173-88c8-0220531c251b   0
  - 4f1a7571-319e-4b08-9a64-aea676a31290   0
  - e4d034ef-4691-43cd-8c8b-4e61ee322dda   0

val:
  - cbf88fa3-f9ea-46ba-ad52-75f4e0364e0a   0
  - 1e57face-9486-4507-a505-8b423400cf76   0

test:
  - a7eb58aa-342a-47b5-a537-c9580c9768f6   0
  - 9f1c46d9-9038-47b4-a227-8af0e5c30bf9   0
  - d078b80c-1cfb-4f23-99ef-598d633ad1d5   0
