version: 1
dataset_version: db-j6gen2-v1.1
train:
- c4edef0a-1d00-4f0d-9e08-65ba8b0692ff   0
- 21dc80db-88f3-4910-ac54-eb8a7000a688   0
- 1e70d931-fbe1-4da9-a606-dec4a4671df4   0
- 293f6501-f51a-4f28-88eb-495776c414a9   0
- 1bed2126-79dc-495f-92e6-9d362947b560   0
- e0305816-afe6-4c89-9b5d-1b8aaab1f8b1   0
- ffc9c66d-8a63-47ca-af28-d79f3aade3e6   0
- 714410ec-97a3-4616-9e5d-ddae4735f971   0
- 18eb9332-7f02-4439-81ed-6b1bae85015b   0
- 0b980836-dc5b-4360-acaa-afb8647a01a4   0
- ada3f8af-0c13-4b09-a024-1d1cf9fce9ec   0
- a1159042-eba8-470a-a193-f13bd7553e05   0
- bfdfc75c-88f8-454d-9bab-02c50c7adfe8   0
- d8db174b-351f-4de1-bb3f-eadd1f3c56db   0
- c00ab3d2-7cdc-49ea-a64a-ad1d1ad31d25   0
- c40d20a5-052f-4df6-ba49-5bd44c33adda   0
- abf183fb-585b-4790-b359-cc11eccba87d   0
- b2805d79-ee76-46d9-918e-d8c0429d501e   0
- 844aaa4c-d865-4977-bb50-8e3ecee6034a   0
- 8ae98627-7502-40f5-a6b0-84c29d7507f8   0
- ca655119-1097-4946-a48e-9248dd27a998   0
- 8e36c4ee-a108-4b9a-9136-a680dd48092a   0
- d9e5a914-eb82-4e43-b178-5a21b7ad3b6a   0
- 3f924950-0147-43d3-a413-1072a0041275   0
- 9a1bdca9-12e3-41cf-8897-491b54f97454   0
- 5f65bfeb-615e-4095-b58d-779639f4eed8   0
- eb17340d-e03a-406b-9e7b-4e9653aa58b1   0
- 569a2d52-3647-48b5-8d8f-35327d5ca38c   0
- d5d1f454-16ff-4c1f-a057-2466e3e830ff   0
- f3dd2806-90f7-4635-b05a-835498d2ac37   0
- 2233e116-8277-4c7f-911b-828da2ecd2dd   0
- 0b228880-111f-4874-84e3-072723cf07cf   0
- 6bcc8ed5-db7e-4885-a04c-fdf2ac053554   0
- 0903f80d-2127-4fd5-a451-466cb7e3a8b5   0
- 8ff95102-7fba-4fcb-8edc-021f87807985   0
- 11bee330-a2ef-432e-b3eb-a496730737f1   0
- 84bfb5c1-5f5c-4ada-a4c7-0da5d2f97afa   0
- 5fdf8e80-4708-423d-ab99-424ae57afec5   0
- fd6d7373-69a7-4eed-b965-c91cd5a7c2c0   0
- 32b9ec1a-c37c-402c-bcb7-7ecc8a344d89   0
- 6d633796-b0a7-476e-a73b-8091a3ea2455   0
- e24ef1c9-b71b-401d-ad93-6b4bf8acd841   0
- e04e8a5a-124b-4bfb-bb16-d7ce5104a9f8   0
- 88c914b3-c7e1-4482-af39-6dafa664ccc4   0
- 3b082c07-17a4-4ab1-b59b-2b60afa78b40   0
- 214cff1b-5a4f-431c-9471-ce8e7be5b9bd   0
- 8e56f624-3801-4514-901e-43f2c51a6280   0
- 8d062098-331a-49fe-b587-2ea2ec048c23   0
- 9b1539d1-7983-42bb-b326-a45165817a4e   0
- d10fa58e-aaff-4a2c-93a0-0cc2445ec1bb   0
- 65785904-4f0a-4e3f-adf7-2935ecdb5db8   0
- 378a3315-869f-4a4e-a2b4-d5600089b990   0
- c687381e-d4da-4b69-8b7c-43824c151ac9   0
- d81f1488-4807-4adc-a168-72cff9349f93   0
- 31c88f97-0675-42f3-b36c-d14aa9e26d84   0
- f373b32f-cce3-4c45-b5ef-96fdd710457a   0
- b4378cfe-350d-4fbb-886b-bc9c49e8a017   0
- 90fab6b0-f332-459d-97b5-0fd145b6eeef   0
- ae5c650b-cdaa-4e4f-84a0-8150c98aefcd   0
- d49d46f3-ba7b-422e-a584-7cabf0e934da   0
- 3a699fc6-e04a-4060-a91d-87a520ba960f   0
- a51583d7-705d-4e39-a789-175fc390199b   0
- 2cca3928-23f0-4d8b-a131-91cf900e7258   0
- 9dd35cdf-caad-4cf7-8ca3-bf5ab0c633bb   0
- 595f13ff-b2d3-4719-8933-1e53f8135444   0
- 259f3915-446a-4427-9290-bae76f6ee7b1   0
- 62858345-5167-4240-8d8e-62edf83ccd56   0
- f61438eb-a42a-4da6-b962-fc1c655074d1   0
- a1740db7-e09c-42e3-ab03-ce13fbe13e4a   0
- 743253bb-051d-49ea-bb0c-dc15579d06cd   0
- eeb68153-97d4-490f-9663-5f71276fd307   0
- c584dbc7-bb4e-4cde-aaa8-4c1fc31c7dd9   0
- b7c23f15-9457-4747-a188-53c128c8c4e2   0
- b5b5ca66-418e-4f35-a2f4-6acc87ad0165   0
- fdb52698-abcf-4677-911e-8a6138a92083   0
- 0258b87e-4db0-4cde-9835-50690484bf6a   0
- dfe7459b-3cbf-4174-83e9-28990b3be7ee   0
- 6443c286-bc34-4ef9-b2e0-11b244867031   0
- 344c0146-7cde-49c6-83d8-6eae7e627e04   0
- 1076ce97-aa5b-491a-9517-0601b5c895db   0
- 795b9cd4-74f8-4a1f-9953-2ff2086ee257   0
- 03844341-96da-4d7d-87db-2da457c5ea83   0
- c56bc53d-17fc-4bc9-bce8-d3082cbabf3f   0
- 6eac0a13-fd47-4514-a69b-09ae5075b58b   0
- fe9503fd-6b83-4cb2-b642-b1ce941af2ed   0
- 68c55674-2aa3-4562-9125-44e4130215fc   0
- 7310101d-22e1-48d3-b1ad-c8a5ea97cc58   0
- f8cb17f9-2387-445a-a722-b384645f32b7   0
- 6b1fa0bb-efc9-4c72-93e4-74a9bacd8f8f   0
- f098c361-129f-4270-b405-6e5c8eeec6f8   0
- d23f4a11-732e-49b1-b1de-403d6ac617b7   0
- 29d72ebb-88cc-42cd-883a-5e9df6cc0d5a   0
- 84299fe1-e056-44db-bb6a-397221741139   0
- d0278d19-3d62-44ba-9fb9-7b515f070d58   0
- 54a09efd-da52-4356-b81e-0162df8d0955   0
- 1ddd8f02-3782-4214-854f-57bb6b1b78ba   0
- 73633449-abfb-42ec-9e63-92b7ba2ba7ba   0
- 51dc87d2-4bed-474a-baec-2e490bae0dac   0
- c6ce0d6c-beb0-46dc-a524-1ab91ac28796   0
- 8e3c4615-d85b-420f-b6a8-a5552a3099dc   0
- 2ba2e509-a85f-4abf-8757-187bd7361655   0
- 2b5aca10-5352-4fa3-a293-89415b9288c3   0
- ffb8f9e3-376b-466c-85d2-e9bef248e8a0   0
- 87f2f1d6-317b-43ce-bd3b-81e266011c68   0
- 9b0265fb-f6f2-4f06-9d44-c465a930c2c5   0
- 0480bf11-2695-428f-9595-a7afc35e35e8   0
- 191f9468-bf32-4962-a175-f739b52f5edf   0
- 4ce57747-1b5c-460f-8c32-54e4d946af97   0
- 6acbcf96-0ff3-4941-9532-6ad2667eed1b   0
- 1a14af8d-271b-4e87-b83f-cd65b1800e24   0
- fd9f502d-d006-4a7f-9cbe-1ab3947f73cf   0
- 886dc55d-ae8d-4d7a-9d7f-5333d4c06d44   0
- 0ddb7026-7a66-4ad9-9637-5c7b46e5a1d6   0
- fefa9268-ec95-4c7f-9cc4-7b4fa0e6a0b7   0
- 428d08b3-432f-4622-b029-97c8de1f491b   0
- 350839ed-a029-45bd-84dd-79f4950ad2af   0
- 60a3cbe3-6a8a-4a38-8379-b3945bf17744   0
- 31605488-1ced-4e3f-a062-2038ff4f5102   0
- b05b2689-a3a4-432b-be7f-c640726f6d26   0
- 79a000c3-8f16-4163-befd-d502a9018e57   0
- bca1132e-b3a9-4161-a02f-2c82273f7078   0
- a43fb447-8266-4103-ac74-61e6323f62b4   0
- f29e397c-d323-40e1-8d27-842ce78c638b   0
- 3dcbec0a-3fe6-437f-86ce-b2b4f6655751   0
- c14c508e-be9a-4738-a6ec-56d9be47e828   0
- 744b629c-d035-4155-92a8-2a58f0f71f2f   1
- 53507f48-638a-49dd-aea5-27a951fccb37   1
- f06f5a0b-9f95-4ac4-8411-5d94d5eb6546   1
- 7055ad26-50d0-4006-96bd-7aca6f4b7995   1
- 83972fd3-024e-4caa-b56e-eec83489b2d9   1
- 4ed09e34-7af3-4f76-bd03-4ff8ca5631b3   1
- 55a6b156-57f1-4bd9-8fee-23820e6147e6   1
- 727eaf20-9866-4cda-aee7-b6f8cf346a94   0
- fa2759b7-a48c-42a1-8d0a-83d86608e4f5   0
- f96f9a8a-0185-4cf9-a9d3-d3438b36b19b   0
- c600dd64-0ba7-48d7-9c88-852c784c9d72   0
- bd216411-3248-48d2-9070-d72a125b2d1e   0
- 216c7c9a-459a-45a3-8cb2-33369ce2705f   0
- b24fd396-9195-4eeb-a629-ab7f964f82e1   0
- d9f9e77c-e8a6-41ff-ba7e-0ed24e73d1cd   0
- a25262c0-83d2-4c28-8151-4f74d5ee2cd5   0
- f3f5f5fe-efc2-495e-8fe8-4ee5401858ee   0
- 72b3092b-f6d7-411c-80b4-7054852e9501   0
- 441b535b-1f7e-4bcf-8c63-c59af2b32fbd   0
- 92436b06-970d-41f6-bdf8-e5bbd4bb23f4   0
- 90207cf1-7503-422a-a1d9-c8df276253c2   0
- 97ab9ab3-e413-4cbe-86c3-f5ba5ffc5b90   0
- 8f74eb60-6418-4871-9311-30943d119d89   0
- 1d6db322-930c-4539-9ce7-13de0ff741a2   0
- dd415fb9-c96d-47ad-bce9-3030610a0f67   0
- da72430c-bcf7-4565-91ae-7c98b4f11e42   0
- 49da6aef-1d12-4a83-ae47-de01cbbf8ed3   0
- 4cc75523-9c3b-4992-8f40-c2f70caaf566   0
- 341b28d7-648f-4030-b577-62a9e1578b55   0
- 6d421208-eb4f-4c5c-bdcc-6c9dd141a8ba   0
- 5593299f-599c-4463-959a-8fd096bd449d   0
- 5798b301-9025-477c-8fb4-6ad5f56b923b   0
- 8bbcf848-2e6b-4e44-b38c-c15320b803e8   0
- bb215e32-3864-4e83-abb2-e61cf1489ee7   0
- c94d1094-3c3b-4d6a-8eec-decf7e44de75   0
- 4b2a3b10-36dd-4ed2-ac4c-d15224ec90a8   0
- 372bd74a-ef5c-49d6-877c-fe37ce7d4038   0
- 9d3ac61a-0114-463d-a91d-6b71146a4ed3   0
- 612fecd2-acdc-44ed-bf61-bd0448452fed   0
- 67a479ee-9bed-4f67-a0ad-f27c2de292b7   0
- 1e1b64fd-c74d-427b-afd1-d78f40e874c9   0
- 36a8a60f-e52a-43cf-b100-121c8ea6e338   0
- 4515235f-84f1-4155-8b4d-525ca47114d9   0
- 2f51b756-9d63-4174-a879-9dcee4b712ba   0
- feaba3b7-d41c-41ee-be4f-720797d0e950   0
- 951e7968-612c-4d4d-949d-762e3fca348d   0
- 7a097ef0-13e2-4541-9e6b-b25e16ba3993   0
- bf5dec71-3ee7-4736-93a7-a654c9483e74   0
- 299a3f1a-c392-4303-88f6-469937c15ea4   0
- b7818cd8-8ce2-44a1-856b-b25eb2517fa8   0
- ea51d87b-beec-4b83-89cf-384dc12879fa   0
- d551205e-2f6c-44ef-a106-8b26af5737e4   0
- 3dfb396a-99e2-4b5a-b2d6-d952a3f024e8   0
- 0b17d36f-b1cc-4082-b73a-cfece71152e7   0
- 830fe144-7973-4d77-bc2c-7ff0d028841e   0
- 8b3896f6-93e1-41d1-8958-10b1dc071fcb   0
- daf8e58b-ec20-49d5-a6d2-3260a03819c4   0
- ed2ee49e-2b6c-40cb-8446-6d7535e77b48   0
- fade2e71-768b-449b-8364-adde0b7d4669   0
- 972a7477-3cfd-4872-af91-7cc90f21a04a   0
- 6d8cbdb0-743f-4a57-8630-f8535e2792b1   0
- 007c45e7-68de-4b98-812b-79719c4ac188   0
- 252993e1-692c-4fb9-80b9-55a1a46773cc   0
- d0f276f3-8391-404f-a920-d5d1baee9975   0
- 891d7974-81ce-4548-89fa-0b6bc9db8449   0
- c1195e65-9825-4d9f-9d0a-ba4660b4df0a   0
- ba310404-b1cc-4aba-912e-c7ce498ef35f   0
- 66ec0c08-1e2e-44ee-a3a8-6d4da5907c1e   0
- 433026e8-f30f-412d-b092-9d8a40b4560f   0
- 6c6df264-43e9-48c3-94f7-60c938e0ff20   0
- bc202b54-1d89-4aff-ae21-c17f16b46fa2   0
- f90d0560-1757-4f32-8fe9-aa11fcca00bc   0
- 1a4564a2-1db4-46a9-b5a3-f56d2a4f5d1d   0
- 09e4f745-5193-45cc-88dd-4fb3b4417510   0
- 9f579e73-1923-4b27-b89e-9df44d15925d   0
- 8da212b2-07db-4cc0-9519-17b14d96616d   0
- 8fcad8e2-b5bc-431d-8e76-12ce4701f25b   0
- 6394a634-c7aa-4e49-b378-d1b46a9e4bbd   0
- 644e5008-8bfc-4949-833e-1b8cfcba18ee   0
- ea87bc96-b6b5-4789-bc92-79467b580fc0   0
- 7a35121b-50e7-4642-b85c-d6f48ba65476   0
- 9e9d3fb0-0300-47f5-915f-0ed107a764f7   0
- 5a857090-fbbd-4056-8cf1-cc88c5a1e1da   0
- 3f0ddd1e-6d9f-4515-aa04-1f80cb197d49   0
- 74d53450-7b60-4c61-bce9-3d624b69135c   0
- 35b7a571-bd41-49a5-84f2-21971c0e9565   0

val:
- 6e398185-4796-44fd-8530-d7d37b046c8e   1
- 77c86ee5-d291-4326-9764-20fa8e9b70c7   1
- 9279b242-db7e-49f6-9937-cafd4a16f3a9   1
- da6f7d0e-03d6-4822-a8a1-5d5444b6ff48   1
- 8c2a9b0e-adc0-4d86-a508-5dffa7cbf547   1
- 9ec83e1b-dc28-4842-8c53-9e00408206b4   1
- 99b61d6e-a150-4254-9630-b4c6fbae73cf   1
- 11d9a8fa-1b5e-4daa-8b2b-1e8c3a3b8867   1
- ea2ea6f1-840d-4230-8f3e-b3d4d7213d45   1
- 800df46b-0da5-4f61-ac2a-02ac885bab71   1
- faef1e90-54bb-45a9-8aea-cb34b3d396fa   1
- 90e45d46-1b17-4303-b20c-e50100c4f91f   1
- 85505582-b7fb-4b8f-8301-d6119c5e0a6b   1

test:
- 3d1e98d5-5f49-4f11-8e6e-90f5652cf103   0
- b93a1ad8-a4f6-48c1-8294-733033f239c5   0
- c9b08447-9181-407c-b74b-548107ad59ae   0
- b9290f79-f1be-4564-8c6a-cca5ff0dea50   0
- d1916c64-63be-4908-a230-9ce4d572b152   0
- f3056f18-b7f6-4469-8d93-d01a283d9a53   0
- 076ff294-daaa-48f0-bc84-17150728490c   0
- a4266053-a7cb-4eba-98a5-59b8c4e16341   0
- fdd8e596-6619-4756-8fd0-83be03ac3d58   0
- ae1ee8f1-3a29-41ef-aa76-3fb92807c500   0
- 8dc97c90-5f34-47c0-bf14-e6708bd22e41   0
- 7d4b7ee5-d1f9-4ccf-b2a9-7734fc84a509   0
- 15ff9788-d9e2-4681-b9a6-8a8cf3e1c100   0
- 25a6a651-1f4b-43d5-b965-fc5af2a57a4e   0
- a043a880-814c-4d20-84bd-61ddcc73bdfd   0
- 93be6ef6-ff58-46d6-a421-892cbd31bd9f   0
- a5c87a89-d376-4f01-807d-d1f5c29df9bd   0
- 9c5d5b18-6f44-4b4c-b851-6dbb65b8491b   0
- 66b60847-6949-4a03-bc4b-958544478379   0
- 8cb01c57-f921-4f14-be28-93fe15ff59e9   0
- 0aa6c28c-ee9d-4d00-9f9a-c7d93b70d9c1   0
- f1a25953-a035-4e06-bc0b-fecb2de6f549   0
- 47dfa06c-07df-4c95-a7ff-59e6792b5584   0
- 0cfde49e-2415-4cdc-9538-6aea1e0410e1   0
- 9d6a4e55-be23-45fd-8904-01ba7b126341   0
- bf21a145-78ae-4043-a883-e46b40c333a2   0
- cf9e8e35-e435-44f2-9922-2bea2d27df19   0
- ffdd0874-fb94-4990-9de6-c1a723babb9f   0
- 4e44f2d4-a780-4f42-8162-d0e3814f21b0   0
- 96448b10-d46c-4811-a370-12fed62fcff1   0
- fa063ed2-b6a1-48be-8e3d-1acde8c6f434   0
- 5bc48ab3-e339-4323-bd29-38d840f767a6   0
- c7621446-d7e3-4fc7-a709-e098adf95c74   0
- 1a99877d-2af1-4b4f-822b-ed4645ca68ef   0
- 0353895d-d857-440c-b8bb-8cdec1732591   0
- 2397597b-b578-4fb0-a7b8-5f0190cf986d   0
- b03bb867-bf67-4313-bce5-13d32cc303ee   0
- 8d5cb8d5-8520-456d-82ed-ce6bc58ad957   0
- e56bacf7-e499-4a8d-8580-7408c82f360e   0
- 2711c7f4-060a-40f6-a165-683d826b46b4   0
- dc7060d8-b0bc-4981-9e22-2239a7dab70b   0
- c2dcadce-006e-4dfa-9c8a-53bffce0673f   0
- 84b85636-92df-4b41-ba73-a6943f665e81   1
- ca5dcc1d-115f-4b92-a7f3-a0a7d74aaf63   1
