version: 1
dataset_version: db-j6gen2-v7.0
train:
  - cc0352c3-97d4-484d-9e67-06384a576d22   0
  - 96505631-4ab1-4da4-b965-34a8a8b3d767   0
  - 34d18993-b8be-491f-8688-cf8aa9ccb577   0
  - 603dd269-d740-49dd-afad-24deb8b44071   0
  - f0bd5239-2dc9-4a3d-9315-15d4e9c7cad1   0
  - 0a75957a-2e2c-47af-8b0a-b2b921f91173   0
  - e21cf4a8-39be-4900-ac0c-9b4b9d9b0a3a   0
  - 72f24a2f-76ab-43e8-8cf1-be244cfe90e5   0
  - 0728917b-aa62-410a-9cc2-ac054dbf9f4c   0
  - d4b7e284-6550-4225-8ddc-de5309cc6f45   0
  - 76ad8203-80d4-4168-b24e-ebeba1b936eb   0
  - 68e38bf9-30aa-4ab2-9dbd-b01ee5502a99   0
  - 76bb1d2e-c7b9-47de-8f3e-648ea2cda3a9   0
  - 18be4516-f8db-4787-99bd-fdb31178c120   0
  - e7892439-f753-4570-ae42-ed2688138373   0
  - 612307a5-e652-4ffa-9199-0e6a2c431562   0
  - 227e51ec-f7c7-4187-91ce-f76a83560e40   0
  - fe588529-2220-4c45-bb36-af1173d4e24c   0
  - 50e7bd10-2fa1-4d1f-ac11-abd14e6c89af   0
  - d317ee40-9753-4836-8a4b-4e82f7e0ca62   0
  - 2fdab25d-9d36-4d10-a94a-ecceb67e54d1   0
  - 99577627-fdc5-432d-a2f9-8338187b8683   0
  - 697ace0e-d016-4953-b8fa-e0d81412b5ee   0
  - 70c11bb0-d788-4f7a-8563-ede639f47f9b   0
  - c8c0cfba-7cc8-421b-a38a-59378c31d09e   0
  - e01ad7d5-7462-46fe-a8a1-4d252365400f   0
  - 4ab9bea5-82e9-48e4-a164-0937a98cb0e6   0
  - 9eafc8f6-eb1c-4f18-ae5d-997af3570129   0
  - ff11375d-1843-4651-affb-9d640bfa62ab   0
  - 9564f14e-c024-42ac-bf48-db5412650e52   0
  - c7cb0940-7b1a-43eb-8de0-21055a525dc7   0
  - 389a537f-efe0-4ad4-bd48-a0e714857445   0
  - 4937aa4f-f50c-4217-a724-63fe7c476c9e   0
  - 898749e1-b625-4d55-bb66-6180847d45ca   0
  - b5ea6467-906c-41fc-b7bc-a577e3dd0410   0
  - 748a439c-79a6-461a-98d7-1feb2bcc7c32   0
  - 8ba19a68-98b9-4a8e-9548-473ddf542b45   0
  - 2219c0c0-0a70-4fe4-9953-7fb0d2c80cff   0
  - fec85fcf-9c1a-478d-bd1e-40b5c2fb587a   0

val: []
test: []
