version: 1
dataset_version: db-j6-v5.0

train:
  - 29c74528-c078-4c09-962b-9e80e1d2fb77
  - 2a7c5c26-211e-41f9-b7fe-6533af15e2f1
  - c5916e94-5505-4dc9-8a7e-56a4dffe99d5
  - cc27948d-e392-4ffa-af63-42ec6e2854e4
  - 19c84260-b3e8-4f94-8548-6271efad031d
  - 60e76c2a-8157-4c4c-8616-b1f24a54b2a5
  - 8e1428ac-475f-443c-a8a9-5f607507c607
  - 8f194ed8-8e41-4cff-81a5-1037a416a7a3
  - deb8922e-dfbb-4916-a8b6-f660661442ce
  - 5379cf30-4c09-4fb3-947b-a4ea68b64cce
  - 5b7b9440-4f49-4571-83ea-c3781dc0fcab
  - b6df27ad-109d-44fc-bae5-12934043a9f9
  - 481f00c9-e9a2-4243-971f-5a7e7c8ae538
  - d559007b-a68b-430c-88cc-2c3c46bbf554
  - 0ec0aa47-0e36-41ad-a251-8bae26213dda
  - 069904b6-3b51-4829-a2c4-a0a9a623e2cc
  - 3bf94928-5f9e-4b2a-9600-ef321c6bba64
  - c53bf92e-b1aa-41e2-8a91-ad8dc0dd7309
  - 75d8e677-dfe3-4369-b2b7-f6786ca83c13
  - 862e5fa8-b737-4af9-96c5-bed51f6899bb
  - dbe5d3cf-072f-46d3-827e-ff951de1cefd
  - 256d4815-7b8f-47be-923b-53f8a0b58cd0
  - e07a228e-29ac-4411-a865-5ff317f03066
  - f003264a-a061-45ea-a7e5-d5ffb6c48941
  - 7aae8667-911b-4311-b672-ddbf3afbf3ce
  - be419b50-ffa6-4926-b9f2-b4f0fdeca028
  - 3ba0a97d-f5ed-4580-b592-a62e0124af04
  - bf516b06-7e05-45d6-963e-e92e30e26735
  - a22fa48e-f7c0-4e17-be76-12fc2e55d909
  - 9484d822-1326-4441-a72c-4e2480a2592b
  - 46156978-5333-490d-96a7-e07634246a11
  - 2b5c9848-17b8-4eed-877b-0ca0f709f12c

val:
  - 77b6ac29-075d-4bf6-8bbf-1ae29420312f
  - 54bad391-5137-40b6-9332-fac9143a728b
  - 0a9192b4-d5a8-4bbb-aea6-993709635ac3

test:
  - 4ad78927-7d63-4487-85c9-7fff6d002dd8
  - 58d6f061-a77c-4f15-b28c-591f1b5f3242
  # - 42776ca4-3bfb-4655-a646-5cf7e74ff0db
