version: 1
dataset_version: db-j6gen2-v6.0

train:
  - 8b8986f9-6277-4af6-abb8-7776e7d2eafb   0
  - 635331de-6ee3-4cba-b531-b2784cba9a81   0
  - 49769a1f-f2d1-43ad-ae00-08b0221bf4c0   0
  - a3acb9b9-a960-4882-bca8-053c0a511194   0
  - 5e747168-a4b1-4a83-8e27-3b1e9a1e2853   0
  - e27ca959-9292-42ba-a343-10896c4bf62a   0
  - 0c46d766-b15c-4a90-8e83-85ecc4cf3bba   0
  - 10a54aa9-9bd5-4ea9-8d8d-ec2b36bc2257   0
  - be492fcc-528a-4044-ae48-547b364c63eb   0
  - 8ac526e8-f47d-4bb8-8fda-18170b603e80   0
  - a8479b47-2c80-4201-86c0-1f27fda7cdc6   0
  - fe468dde-733e-408c-85f9-c141098cb395   0
  - 25459ef4-8101-4237-8c68-72443c90c686   0
  - ae813e0b-82fc-4e83-9f3c-ade961ec19b6   0
  - daf21476-3cf1-48fe-bf79-f31b2850d943   0
  - fb24f56f-39a9-4662-a3eb-9eb7dd1d8383   0
  - c37067a6-8a1c-421b-b0a0-86fa112366d1   0
  - 76397598-f11d-4b79-b19b-1456880028bd   0
  - b5eb671a-4e13-4c43-bc30-07cc6ea2fc5c   0
  - 68857d3f-64d2-46c8-a151-10105b9be7fc   0
  - 05a74699-f5b5-44b5-81b0-cbab89eca6e2   0
  - bd94bb66-2695-408b-8888-05f4f9ad0c4e   0
  - a9cc9df7-feb1-42b1-a493-7e280399046d   0
  - 10505320-f8bf-4650-99a9-2d42af9aab4e   0
  - aed19cd8-5a62-4e61-85e5-78a7e0009892   0
  - 9fc9b046-f3e0-42d9-bcd4-6ffefc7fbfb0   0
  - 2681cd41-204e-4f73-94cd-b12a7110a5bb   0
  - 01ad027f-f43c-4cbc-8006-13eee1a2a746   0
  - 0a4e2acb-ab40-4ea0-baf3-30fb392a4d63   0
  - b1ee4dc7-0d48-4951-890e-d69ebd1cd187   0
  - 2fb33f0b-4b7e-4178-8d1a-10f290964bfa   0
  - 99ae8cb1-bf61-4733-8a57-b0bd40e11dae   0
  - 4b016222-0d28-443d-8bec-b42eb8620dba   0
  - 5ba135e1-7205-464d-ae1c-d5607ce4b11f   0
  - a25a943f-ba7e-4d82-b934-607a12725426   0
  - 1db131e3-6864-4c0d-af20-50bbd2888061   0
  - dcedffbc-e74a-4e80-a060-9167fec406e3   0
  - 8cc7bfa0-97ca-45e9-b8a4-624d71c0ca3c   0
  - cbbdff12-c9e9-4f3b-9a3f-ee82b5372463   0
  - 9c15482a-2277-4e7d-ad2e-7f8ed1dd0c75   0
  - 5a678c76-32d5-4090-b7b0-224143f96d23   0
  - a2b1b15b-ac8e-4c24-ad32-d2da5dca75d4   0
  - ade55bee-4206-4192-bd32-b365d3340e8c   0
  - b4bce67c-12c0-4027-90d0-75117ca6db49   0
  - 7129976b-d142-4dc2-bde1-861f5a2fb709   0
  - d9d943f2-c850-4d0c-a25e-ad8b6cf53e49   0
  - 94ee8276-837f-4664-99f6-dc5646b3229d   0
  - eb1d5313-32c4-4b79-bbb8-e4601641e1e9   0
  - abc46078-301c-4608-bd16-b8e2030b6f30   0
  - 3f104b24-f7c2-43e5-982e-13b57b1ab73d   0
  - 2f5e5ccb-e8ea-490a-accf-aaa807858fe7   0
  - 69c16991-03a4-415e-8e69-6184a07d8358   0
  - 60d5c671-98c0-4edf-9263-29be9f2eea32   0
  - 8222121a-5e0f-430f-a0cd-977c3cb43e15   0
  - 59c0f674-a300-4b23-bc40-9331e262dc77   0
  - 30490e59-0c81-4f5f-9a78-7b513bf7a3eb   0
  - 9cc0faab-e20e-4e63-abbf-81fc2330c1b1   0
  - e53f69f1-acb3-49b6-9446-96d65f5edde2   0
  - a72a658d-87e2-4094-ada9-1b21f645236d   0
  - 6f975a25-64be-42ad-a45f-74766d9872ac   0
  - 00a49cfe-a048-454b-a15f-741e662751f7   0
  - 67525403-3c52-4e57-b6ce-dc69453e2e25   0
  - 6f1a61de-66c7-437f-aa45-aeae3b38358c   0
  - 918fcc7f-95bf-4c62-a7d8-8938763f4429   0
  - be5cca18-5cd2-4a5e-805d-66410fc19598   0
  - 46d86907-418f-42da-9417-dc470f2efb5d   0
  - c53d3b7e-601f-4e10-a40e-6ed45a6f794a   0
  - b1ecf7a6-3ed5-4b25-80c5-49689d9a2d07   0
  - aabf1923-3a4a-4561-8d21-4e61d3d2edf4   0
  - e0e5dc30-db4d-4731-9432-2f2d35f39869   0
  - 789db51e-c122-4ea3-8261-5c3ebc12c084   0
  - 59a78048-b0f1-4f65-8659-170709c84492   0
  - 907a3f8e-15c2-4de0-8da9-1e33be6ae492   0
  - c9423f79-5c17-4eb8-9ff1-ef532782619b   0
  - 78054ac6-9ac4-48cf-9de2-16b860c79872   0
  - d91bc935-edaf-4e99-914f-6d55466c16e9   0
  - e3197e91-27f1-4972-aac5-6194618e640b   0
  - 0376e770-6114-42eb-93bb-abda4866f797   0
  - 9ba0d824-195e-4c8e-8192-7a18343f8549   0
  - 3d22a571-007a-4f83-9203-2f2dafaa7feb   0
  - da95e33b-66b7-4ac8-bd02-7ac071a8ad8b   0
  - 1b951cad-e28a-4140-8f9c-6c3058217c7b   0
  - 7095b455-7b22-4666-8a92-c95e31432af2   0
  - 859ebcc6-736a-4dec-bffd-f8f9da549d98   0
  - 11dbc93d-e270-45c4-9143-7c1222c80225   0
  - 23b0bfc1-b8cc-4112-b060-34d5b407a287   0
  - c57a52fc-750e-4b46-9655-e2ec2b8f4352   0
  - c3131c08-79fd-4087-9e92-62c8492c279d   0
  - 7e256797-1689-4d89-96a4-3f84eef922bc   0
  - 1d21b47e-6b1a-4858-b235-2532a2882661   0
  - 2921886e-82b8-48b2-8e36-f9eb95691a00   0
  - 76b60afc-bbb4-40d8-b07a-073e939a81ec   0
  - a488b851-22ab-4939-ba29-acbbda2a8c9f   0
  - 9c0bf511-9070-4430-bfb6-41f67f4abb51   0
  - 7f3212ed-adf4-458e-badd-83475a5322dd   0
  - 75eaaa3e-062c-45f6-aac7-2549a0da4ed3   0
  - 9b649da3-7ed6-40b3-b7a8-9b7dddf52372   0
  - 39f08686-ef55-419b-bbd7-b783b8f23f39   0
  - 9f15e05a-d88a-4981-b2cb-370a273a54c3   0
  - 1f535f4a-63ef-49a8-9d99-dd103009f131   0
  - c4b9a3ec-5054-4aaa-b740-36331f814979   0
  - aa6b614a-e031-4221-a26d-8288fa6817f2   0
  - 3c21893d-f719-464b-97a3-19756bdbd74a   0
  - 84f61d96-c5f1-433a-aeb3-662957309d93   0
  - 98785eae-7f42-43f0-abc3-f48e06eecdb3   0
  - 51c4a5ef-52ab-494d-b6b9-356b0f3df39e   0
  - 42905515-cdb9-4494-93ea-815dc2d437e4   0
  - 19e96984-fa84-4112-9a50-5056fb5c3c2b   0
  - 92e3670f-1fa1-41cc-9fd7-85c01fdfde04   0
  - c5f7b51a-1ef8-4a4b-9ac3-349a8216a7f9   0
  - 62f5585f-cdfe-4dce-b121-c58b18ec6253   0
  - a79cd769-7312-4061-9773-601b1dfe218e   0
  - 99e7787b-f094-483b-ad35-a86952ef034a   0
  - 131550f5-d763-4962-a5dd-ecc9140e1f67   0
  - 0b0dbc24-15ef-4e93-8e73-315a73276ee0   0
  - 0067ba87-5b6d-463a-a751-8418d6da5f63   0
  - 28595741-03b7-4435-8586-ea8325bf4aa2   0
  - fcb5adcb-1e1f-4c9f-80fa-95c273348ad7   0
  - a23e9922-f4c6-4261-8ae8-c2cdd55c2103   0
  - 86d1425b-5f4c-44fb-800e-e49a94448dde   0
  - 6d562abe-4490-4934-a2ea-d738547564bf   0
  - 1c98dec2-5aea-44e7-ba1c-c5a09bea44b4   0
  - a529d524-d54c-4e91-9492-5bd5c74f7daf   0
  - 45435e46-c4cc-4c66-ab89-6220a2118be5   0
  - 6f0d68be-83f3-401d-9ce0-6416052be679   0
  - 6838f906-b11e-4426-8670-f5eb45122530   0
  - 780e18ea-a4e5-4fad-b68a-97d2a87c18d6   0
  - 846d0c6f-aa7b-4db4-8bb2-1b78115823b5   0
  - 29d0404c-999f-49a5-97b7-600546a0f2e0   0
  - 61db27fc-282a-4e37-9615-adc90b1f221c   0
  - c81e28ac-5753-474f-9939-f3f8a3c12c6c   0
  - 813beeef-0c1c-497f-91b5-da8adf509496   0
  - 1edf94e2-d0a4-432d-9b59-99149537e5be   0
  - 89eb82ef-97bb-4e2b-888c-6462a9744353   0
  - 31a51796-c9bd-4395-bd41-55a1219ae215   0
  - be7144a5-6fe5-4c4f-aa23-1bed1a7df0bc   0
  - 84c61ec7-6373-4de5-98ca-60513c8c1703   0
  - 312c10a2-51e1-4ab6-a32a-8cf06475f744   0
  - 474be0f9-207f-4a78-9e13-68a4aa669bbf   0
  - 83cc7162-4df3-4da0-8763-0b57dd2a8d91   0
  - 787e1904-81e6-4ec8-b6a2-3f67f8858de4   0
  - 139f4c0c-a1f4-4f62-970a-f3931ee32ee1   0
  - a700c09a-40bc-4d23-afcb-2c357ab72365   0
  - b4265887-95f3-4d84-8622-3c4fefd3bb11   0
  - df949ce6-3f58-4bfc-bfaa-28c154d975e3   0
  - f9b01673-c500-4085-b209-a9802a6072b5   0
  - bc11cb39-887a-41b7-b5e9-fb139371f630   0
  - fd5108a3-e2e5-47ae-a7cb-b7b6e36c6915   0
  - 542eb562-82dd-4db3-9dbb-53deddc608bf   0
  - 3c31b06f-3a60-4949-9fbd-cdd3d15485d7   0
  - 99e0955e-34c1-46a4-97c2-cc13239819d6   0
  - 77ecc410-9815-483d-a0de-0f9e4fe4ed2c   0
  - 871886e4-3788-4eda-9bdb-3f5700abde43   0
  - 3fe8d6ad-cb9a-4c52-91d9-9445879c4df9   0
  - 29587872-8b62-4731-a6b6-a53131221a2d   0
  - 9666deb0-cfc0-4ea3-9725-9644edc98346   0
  - 4001acfd-22b9-42a2-86f3-8b70002e6dae   0
  - ddcc117a-b59e-4c1f-ac67-a5acbebc89ec   0
  - 9767b69d-324a-474d-8bbf-a2e75e86a19e   0
  - d7c79ad9-4832-404d-868f-cafff237852b   0
  - 46f2d61b-4b6f-432c-80f7-9804804e2f7c   0
  - a6e12195-04b6-4dc7-bc4f-2e156c3c2a9d   0
  - 7220b153-69b2-41c9-910f-b885de712a80   0
  - 00773ab1-146e-4b8f-b3b5-617337224bad   0
  - c4b4231d-6e68-49a0-8828-fc70ed0b93ff   0
  - 828cbc27-60b2-4ddc-a79b-3a9933ff69d5   0
  - fff67bf7-82ee-4e0a-abee-899e4c603636   0
  - 69502535-11e8-4231-a36e-20482d39991e   0
  - 90809dc5-0dcc-4eef-a32a-b3b8cf6afd1b   0
  - 52cbbb2a-85a7-4a7e-b15f-87e518b3fecf   0
  - 786c148d-8b50-457d-9cd3-68a3d9d6eecf   0
  - b23b8a80-9313-4e86-8453-e34cf0c6eff6   0
  - 414d4868-7184-4710-ade6-449310480164   0

val:
  - e7298df7-6490-4541-a56e-24f109b868f2   0
  - ee8077db-3011-4840-9566-a324d3326378   0
  - a8ded668-e02d-49df-9ce2-24126b65fcad   0
  - bc3c2bf6-9e97-4475-ae5e-ce039c905946   0
  - 06b5e0df-b493-4152-b68a-984b55330cde   0
  - 5ae60ca0-89db-458c-80a3-26f40e662f04   0
  - d653b768-e345-4839-9179-a4e2cd14890b   0

test:
  - b8e76829-6de4-4955-b661-cbaa2c9bf091   0
  - e5bb8b7d-12b6-41ef-99fe-0ea0e11b584c   0
  - 28a43203-f774-40c9-a694-cbfc41fdfd4d   0
  - 83ec6d3d-13a8-4e3a-85f9-f8a81a8a6a88   0
  - 18226260-30d9-4b5c-a8d3-ebb1e985cd47   0
  - 07336aa6-ff97-45f5-ae94-5be7f2c0020d   0
  - d9ab001d-b412-4366-a7a6-a810aa552f4a   0
  - d15170e0-58aa-4997-92d4-f571cd08617d   0
  - 5b757197-5205-4662-b4ed-c70b6cd40107   0
  - 5c897e34-aa08-4a6f-98c9-545e37b4f492   0
  - 9720fdc8-2ab8-4f40-a412-9eb8c2a70ae4   0
  - 029e609d-19d5-4e04-9acf-931dbaca8056   0
  - e79e7f56-35cf-4db9-92f6-1ac6346b428c   0
  - fa1b652c-9faf-4b0b-a7ae-361d1e707c81   0
  - 142aa93a-67cb-445e-b503-f88b6d72932d   0
  - d2ea7ccc-29ad-4f37-856b-6fde5ecfd14a   0
