version: 1
dataset_version: db-j6gen2-v1.1

train:
  - c4edef0a-1d00-4f0d-9e08-65ba8b0692ff
  - 21dc80db-88f3-4910-ac54-eb8a7000a688
  - 1e70d931-fbe1-4da9-a606-dec4a4671df4
  - 293f6501-f51a-4f28-88eb-495776c414a9
  - 1bed2126-79dc-495f-92e6-9d362947b560
  - e0305816-afe6-4c89-9b5d-1b8aaab1f8b1
  - ffc9c66d-8a63-47ca-af28-d79f3aade3e6
  - 714410ec-97a3-4616-9e5d-ddae4735f971
  - 18eb9332-7f02-4439-81ed-6b1bae85015b
  - 0b980836-dc5b-4360-acaa-afb8647a01a4
  - ada3f8af-0c13-4b09-a024-1d1cf9fce9ec
  - a1159042-eba8-470a-a193-f13bd7553e05
  - bfdfc75c-88f8-454d-9bab-02c50c7adfe8
  - d8db174b-351f-4de1-bb3f-eadd1f3c56db
  - c00ab3d2-7cdc-49ea-a64a-ad1d1ad31d25
  - c40d20a5-052f-4df6-ba49-5bd44c33adda
  - abf183fb-585b-4790-b359-cc11eccba87d
  - b2805d79-ee76-46d9-918e-d8c0429d501e
  - 844aaa4c-d865-4977-bb50-8e3ecee6034a
  - 8ae98627-7502-40f5-a6b0-84c29d7507f8
  - ca655119-1097-4946-a48e-9248dd27a998
  - 8e36c4ee-a108-4b9a-9136-a680dd48092a
  - d9e5a914-eb82-4e43-b178-5a21b7ad3b6a
  - 3f924950-0147-43d3-a413-1072a0041275
  - 9a1bdca9-12e3-41cf-8897-491b54f97454
  - 5f65bfeb-615e-4095-b58d-779639f4eed8
  - eb17340d-e03a-406b-9e7b-4e9653aa58b1
  - 569a2d52-3647-48b5-8d8f-35327d5ca38c
  - d5d1f454-16ff-4c1f-a057-2466e3e830ff
  - f3dd2806-90f7-4635-b05a-835498d2ac37
  - 2233e116-8277-4c7f-911b-828da2ecd2dd
  - 0b228880-111f-4874-84e3-072723cf07cf
  - 6bcc8ed5-db7e-4885-a04c-fdf2ac053554
  - 0903f80d-2127-4fd5-a451-466cb7e3a8b5
  - 8ff95102-7fba-4fcb-8edc-021f87807985
  - 11bee330-a2ef-432e-b3eb-a496730737f1
  - 84bfb5c1-5f5c-4ada-a4c7-0da5d2f97afa
  - 5fdf8e80-4708-423d-ab99-424ae57afec5
  - fd6d7373-69a7-4eed-b965-c91cd5a7c2c0
  - 32b9ec1a-c37c-402c-bcb7-7ecc8a344d89
  - 6d633796-b0a7-476e-a73b-8091a3ea2455
  - e24ef1c9-b71b-401d-ad93-6b4bf8acd841
  - e04e8a5a-124b-4bfb-bb16-d7ce5104a9f8
  - 88c914b3-c7e1-4482-af39-6dafa664ccc4
  - 3b082c07-17a4-4ab1-b59b-2b60afa78b40
  - 214cff1b-5a4f-431c-9471-ce8e7be5b9bd
  - 8e56f624-3801-4514-901e-43f2c51a6280
  - 8d062098-331a-49fe-b587-2ea2ec048c23
  - 9b1539d1-7983-42bb-b326-a45165817a4e
  - d10fa58e-aaff-4a2c-93a0-0cc2445ec1bb
  - 65785904-4f0a-4e3f-adf7-2935ecdb5db8
  - 378a3315-869f-4a4e-a2b4-d5600089b990
  - c687381e-d4da-4b69-8b7c-43824c151ac9
  - d81f1488-4807-4adc-a168-72cff9349f93
  - 31c88f97-0675-42f3-b36c-d14aa9e26d84
  - f373b32f-cce3-4c45-b5ef-96fdd710457a
  - b4378cfe-350d-4fbb-886b-bc9c49e8a017
  - 90fab6b0-f332-459d-97b5-0fd145b6eeef
  - ae5c650b-cdaa-4e4f-84a0-8150c98aefcd
  - d49d46f3-ba7b-422e-a584-7cabf0e934da
  - 3a699fc6-e04a-4060-a91d-87a520ba960f
  - a51583d7-705d-4e39-a789-175fc390199b
  - 2cca3928-23f0-4d8b-a131-91cf900e7258
  - 9dd35cdf-caad-4cf7-8ca3-bf5ab0c633bb
  - 595f13ff-b2d3-4719-8933-1e53f8135444
  - 259f3915-446a-4427-9290-bae76f6ee7b1
  - 62858345-5167-4240-8d8e-62edf83ccd56
  - f61438eb-a42a-4da6-b962-fc1c655074d1
  - a1740db7-e09c-42e3-ab03-ce13fbe13e4a
  - 743253bb-051d-49ea-bb0c-dc15579d06cd
  - eeb68153-97d4-490f-9663-5f71276fd307
  - c584dbc7-bb4e-4cde-aaa8-4c1fc31c7dd9
  - b7c23f15-9457-4747-a188-53c128c8c4e2
  - b5b5ca66-418e-4f35-a2f4-6acc87ad0165
  - fdb52698-abcf-4677-911e-8a6138a92083
  - 0258b87e-4db0-4cde-9835-50690484bf6a
  - dfe7459b-3cbf-4174-83e9-28990b3be7ee
  - 6443c286-bc34-4ef9-b2e0-11b244867031
  - 344c0146-7cde-49c6-83d8-6eae7e627e04
  - 1076ce97-aa5b-491a-9517-0601b5c895db
  - 795b9cd4-74f8-4a1f-9953-2ff2086ee257
  - 03844341-96da-4d7d-87db-2da457c5ea83
  - c56bc53d-17fc-4bc9-bce8-d3082cbabf3f
  - 6eac0a13-fd47-4514-a69b-09ae5075b58b
  - fe9503fd-6b83-4cb2-b642-b1ce941af2ed
  - 68c55674-2aa3-4562-9125-44e4130215fc
  - 7310101d-22e1-48d3-b1ad-c8a5ea97cc58
  - f8cb17f9-2387-445a-a722-b384645f32b7
  - 6b1fa0bb-efc9-4c72-93e4-74a9bacd8f8f
  - f098c361-129f-4270-b405-6e5c8eeec6f8
  - d23f4a11-732e-49b1-b1de-403d6ac617b7
  - 29d72ebb-88cc-42cd-883a-5e9df6cc0d5a
  - 84299fe1-e056-44db-bb6a-397221741139
  - d0278d19-3d62-44ba-9fb9-7b515f070d58
  - 54a09efd-da52-4356-b81e-0162df8d0955
  - 1ddd8f02-3782-4214-854f-57bb6b1b78ba
  - 73633449-abfb-42ec-9e63-92b7ba2ba7ba
  - 51dc87d2-4bed-474a-baec-2e490bae0dac
  - c6ce0d6c-beb0-46dc-a524-1ab91ac28796
  - 8e3c4615-d85b-420f-b6a8-a5552a3099dc
  - 2ba2e509-a85f-4abf-8757-187bd7361655
  - 2b5aca10-5352-4fa3-a293-89415b9288c3
  - ffb8f9e3-376b-466c-85d2-e9bef248e8a0
  - 87f2f1d6-317b-43ce-bd3b-81e266011c68
  - 9b0265fb-f6f2-4f06-9d44-c465a930c2c5
  - 0480bf11-2695-428f-9595-a7afc35e35e8
  - 191f9468-bf32-4962-a175-f739b52f5edf
  - 4ce57747-1b5c-460f-8c32-54e4d946af97
  - 6acbcf96-0ff3-4941-9532-6ad2667eed1b
  - 1a14af8d-271b-4e87-b83f-cd65b1800e24
  - fd9f502d-d006-4a7f-9cbe-1ab3947f73cf
  - 886dc55d-ae8d-4d7a-9d7f-5333d4c06d44
  - 0ddb7026-7a66-4ad9-9637-5c7b46e5a1d6
  - fefa9268-ec95-4c7f-9cc4-7b4fa0e6a0b7
  - 428d08b3-432f-4622-b029-97c8de1f491b
  - 350839ed-a029-45bd-84dd-79f4950ad2af
  - 60a3cbe3-6a8a-4a38-8379-b3945bf17744
  - 31605488-1ced-4e3f-a062-2038ff4f5102
  - b05b2689-a3a4-432b-be7f-c640726f6d26
  - 79a000c3-8f16-4163-befd-d502a9018e57
  - bca1132e-b3a9-4161-a02f-2c82273f7078
  - a43fb447-8266-4103-ac74-61e6323f62b4
  - f29e397c-d323-40e1-8d27-842ce78c638b
  - 3dcbec0a-3fe6-437f-86ce-b2b4f6655751
  - c14c508e-be9a-4738-a6ec-56d9be47e828
  - 744b629c-d035-4155-92a8-2a58f0f71f2f
  - 53507f48-638a-49dd-aea5-27a951fccb37
  - f06f5a0b-9f95-4ac4-8411-5d94d5eb6546
  - 7055ad26-50d0-4006-96bd-7aca6f4b7995
  - 83972fd3-024e-4caa-b56e-eec83489b2d9
  - 4ed09e34-7af3-4f76-bd03-4ff8ca5631b3
  - 55a6b156-57f1-4bd9-8fee-23820e6147e6

val:
  - 6e398185-4796-44fd-8530-d7d37b046c8e
  - 77c86ee5-d291-4326-9764-20fa8e9b70c7
  - 9279b242-db7e-49f6-9937-cafd4a16f3a9
  - da6f7d0e-03d6-4822-a8a1-5d5444b6ff48
  - 8c2a9b0e-adc0-4d86-a508-5dffa7cbf547
  - 9ec83e1b-dc28-4842-8c53-9e00408206b4
  - 99b61d6e-a150-4254-9630-b4c6fbae73cf
  - 11d9a8fa-1b5e-4daa-8b2b-1e8c3a3b8867
  - ea2ea6f1-840d-4230-8f3e-b3d4d7213d45
  - 800df46b-0da5-4f61-ac2a-02ac885bab71
  - faef1e90-54bb-45a9-8aea-cb34b3d396fa
  - 90e45d46-1b17-4303-b20c-e50100c4f91f
  - 85505582-b7fb-4b8f-8301-d6119c5e0a6b

test:
  - 3d1e98d5-5f49-4f11-8e6e-90f5652cf103
  - b93a1ad8-a4f6-48c1-8294-733033f239c5
  - c9b08447-9181-407c-b74b-548107ad59ae
  - b9290f79-f1be-4564-8c6a-cca5ff0dea50
  - d1916c64-63be-4908-a230-9ce4d572b152
  - f3056f18-b7f6-4469-8d93-d01a283d9a53
  - 076ff294-daaa-48f0-bc84-17150728490c
  - a4266053-a7cb-4eba-98a5-59b8c4e16341
  - fdd8e596-6619-4756-8fd0-83be03ac3d58
  - ae1ee8f1-3a29-41ef-aa76-3fb92807c500
  - 8dc97c90-5f34-47c0-bf14-e6708bd22e41
  - 7d4b7ee5-d1f9-4ccf-b2a9-7734fc84a509
  - 15ff9788-d9e2-4681-b9a6-8a8cf3e1c100
  - 25a6a651-1f4b-43d5-b965-fc5af2a57a4e
  - a043a880-814c-4d20-84bd-61ddcc73bdfd
  - 93be6ef6-ff58-46d6-a421-892cbd31bd9f
  - a5c87a89-d376-4f01-807d-d1f5c29df9bd
  - 9c5d5b18-6f44-4b4c-b851-6dbb65b8491b
  - 66b60847-6949-4a03-bc4b-958544478379
  - 8cb01c57-f921-4f14-be28-93fe15ff59e9
  - 0aa6c28c-ee9d-4d00-9f9a-c7d93b70d9c1
  - f1a25953-a035-4e06-bc0b-fecb2de6f549
  - 47dfa06c-07df-4c95-a7ff-59e6792b5584
  - 0cfde49e-2415-4cdc-9538-6aea1e0410e1
  - 9d6a4e55-be23-45fd-8904-01ba7b126341
  - bf21a145-78ae-4043-a883-e46b40c333a2
  - cf9e8e35-e435-44f2-9922-2bea2d27df19
  - ffdd0874-fb94-4990-9de6-c1a723babb9f
  - 4e44f2d4-a780-4f42-8162-d0e3814f21b0
  - 96448b10-d46c-4811-a370-12fed62fcff1
  - fa063ed2-b6a1-48be-8e3d-1acde8c6f434
  - 5bc48ab3-e339-4323-bd29-38d840f767a6
  - c7621446-d7e3-4fc7-a709-e098adf95c74
  - 1a99877d-2af1-4b4f-822b-ed4645ca68ef
  - 0353895d-d857-440c-b8bb-8cdec1732591
  - 2397597b-b578-4fb0-a7b8-5f0190cf986d
  - b03bb867-bf67-4313-bce5-13d32cc303ee
  - 8d5cb8d5-8520-456d-82ed-ce6bc58ad957
  - e56bacf7-e499-4a8d-8580-7408c82f360e
  - 2711c7f4-060a-40f6-a165-683d826b46b4
  - dc7060d8-b0bc-4981-9e22-2239a7dab70b
  - c2dcadce-006e-4dfa-9c8a-53bffce0673f
  - 84b85636-92df-4b41-ba73-a6943f665e81
  - ca5dcc1d-115f-4b92-a7f3-a0a7d74aaf63
