version: 1
dataset_version: db-largebus-v2.0
train:
  - f325e503-07bc-4f6c-aa58-7e27bf054408   0
  - 0fabc948-8368-4465-bd5d-f135df0b7013   0
  - 2f4dc4f5-32ed-4d77-b389-680f174e979d   0
  - 08785d32-80e5-489c-972f-acdbf668fee2   0
  - 59114f5f-1090-4672-83fe-e19382243d27   0
  - 39e56516-b13d-4b95-844a-dce068a2227f   0
  - 7700c5b8-29c6-4f76-9873-dc0dedc209ef   0
  - c5220774-fd68-4e8a-b519-f06a04809261   0
  - 0ff4efe1-0551-45a9-8fcd-dff67fd7d0d3   0
  - dbd3cd9b-986c-4cb0-ab28-81c5276e17b4   0
  - fc29e9a0-82d0-42a3-90a2-d569c8808ece   0
  - 2c537caa-68c9-4256-a286-33241fdde25f   0
  - 612ca964-0796-4789-a0e8-fafa1c40a5f5   0
  - 739d43cb-8bd3-400a-b8b3-478ca63ac7a2   0
  - 1c519a3f-6367-4617-8fc0-73081096711b   0
  - b54af232-a6d7-4ec0-8460-5d3c8bf5eac0   0
  - c4ef1561-f888-4981-aa84-2ceaad43dc87   0
  - 372fb3fe-af12-44e4-9d32-93fb5e3afee3   0
  - 86f695ce-7e83-4829-a75b-9c75c0c7fddc   0
  - 59bb1df3-7bb8-4525-bbdd-9f428354c49e   0
  - e1f8a3c2-79bd-4a75-9816-de698237d890   0
  - 8bd2930c-7469-4464-97b8-a8e5c3bb0727   0
  - e18d28dd-0ab6-44ac-b8cc-250f168f6e4e   0
  - 376e01bf-3dd5-4ec2-b95e-8aa7b93e5de4   0
  - b01272fd-cff9-40b7-999e-eee306c07747   0
  - 7aa19f00-504b-43cb-846f-8a6421e344ad   0
  - 716925f2-abed-413a-b932-b31184e77e6f   0
  - 556529ba-8536-4ba8-abcd-3d35ce9c97b7   0
  - 80a2b30c-4983-42d9-a0a7-715940d4a1d2   0
  - a66973d6-4a90-4166-8310-500c81e0c036   0
  - cc2c8eff-f4bf-4b47-a129-cd1abe1a14bd   0
  - b7ce04a0-731b-4cfc-af10-f5932976bee3   0
  - ed27115c-a063-4348-bc8b-2f3bbf85de9d   0
  - bbfd205c-e595-467d-b188-ea7e31936d82   0
  - feae5b35-d51f-4858-a320-d83d234f397f   0
  - 94033f4d-5dd4-489f-8450-818a82e33f93   0
  - 758d4cd3-8889-4edb-8bc4-a5a8dc7e4fd0   0
  - 04cea3fb-b9af-4e47-b996-4ebb347587e9   0
  - 4b67d8f7-8da4-4c57-9f74-4c5964d7351d   0
  - 6c1e478f-8ade-4493-8e00-5af7f94fc291   0
  - 2773f049-6666-4440-9730-d06ce1fe008c   0
  - 868f1e7e-627c-426c-9899-36926162e392   0
  - 862e2062-c9f5-4fe4-a841-341c363a3f88   0
  - 2cdb753a-59cd-4c69-9ba7-28d7a0fd5c83   0
  - c5ed9b83-ff1d-4a0f-bc06-2536ee75a085   0
  - b6ddcf6d-1fc2-4af3-93a5-c7ffccbeb9ad   0
  - 871fa54b-3ea4-407c-8342-d5f867c94e03   0
  - fb674559-b33f-4a5e-a514-b454ea973046   0
  - 7184a564-53ac-44a4-94d5-993ad6a19de5   0
  - 6ecbc629-5e63-4117-b687-5d7de007d730   0
  - d6af45c5-4ff7-4dc0-a5dd-84f07e4ba445   0
  - d3bd36ef-1511-498c-b113-c6bef4ac5221   0
  - b075b01b-e144-43d0-a890-3b132bbe0a3f   0
  - 4185b56f-bc6a-4a79-a31b-543c78924688   0
  - 01a32fba-de0f-4e56-b51f-3f075e404e8f   0
  - 3c9eabb9-34db-426a-907c-cd09f04b5edc   0
  - 191b3fd5-2e01-4e5f-8c0a-19148ef7d204   0
  - 8650aba6-6c01-46d8-bd5c-ce287abb94c0   0
  - 54fce2d0-78c0-4781-af3b-ecaf03aa295e   0
  - b46ff80a-e8cc-4dc8-8bac-f333a2b89e4f   0
  - dba9dd2f-7673-49c1-9ba0-1cba0c4c93b1   0
  - 1980d46c-d27f-4517-af2b-cc44a3df804c   0
  - 5d0e8213-32b8-4fc2-a414-3831add15632   0
  - 586e5e15-ad62-45f8-a930-27cbf1696126   0
  - 926bcaad-af3e-4b4d-8f34-ea2b39384b52   0
  - 1f4b375e-913b-452e-ba51-cb126f499d23   0
  - b538e158-ca0e-48bd-941b-7d2976e745ee   0
  - 143843c2-877e-4d16-a370-aabd00ca4291   0
  - efe2ee8f-9c25-4e55-bbdd-443042a3a190   0
  - 3cf7f907-d875-4251-a6f1-081648642eab   0
  - e0b52b9b-814d-4d1e-a2c6-db05e257bb3c   0
  - 92897540-4011-4e3e-accf-ad3c26208aa5   0
  - b57628b9-3430-4a0e-b4e3-44fd9c570ed8   0
  - 49699b59-ea03-408e-88e9-47033c0919c0   0
  - df2db2b3-8c7a-402f-9362-98650f07cff4   0
  - 35ad77e3-39c1-4a00-a2e2-efab3c9467fd   0
  - 9f2fad8b-2606-4f3a-96f7-0edda691e75d   0
  - 9839e466-98ca-47dc-872c-ee7ae93a9500   0
  - 08ce4233-9a9c-41db-91f9-edf427869956   0
  - c05dcbdd-def6-49f2-bd26-53f99f46dc8a   0
  - e904db78-c518-4bc1-ba68-b9658c5f0211   0
  - 51e3337e-ac07-476a-b148-a9384ca05e71   0
  - 14a6f6c4-4b51-4a7b-ba22-b3d467d6bc79   0
  - 0a1fc549-6d26-489c-97e5-97dba7aa8b24   0
  - 5d8be418-0762-4437-998c-4fc3a14d452b   0
  - 1f602c14-9447-42d7-97eb-e702e7074c7c   0
  - 2ab9432b-bf32-468e-8b7f-afc326acfe71   0
  - 5c7294e7-deee-4e03-9344-c217d467af7d   0
  - bdd52b2d-8573-413e-aafb-a629d74f5976   0
  - cefd3a70-9627-4c3c-b007-6a23f47a8d50   0
  - c11e787f-c7d2-48a3-98a3-8ab280cd1cc7   0
  - 43734163-9be7-4d49-9111-2d9e065fecd7   0
  - fe698bc6-ebeb-4915-9399-681b404ed1fa   0
  - 65327ee4-6910-466e-98c9-0d0e59bb6feb   0
  - 8d9204a1-2d33-42bc-908a-1c05341e4e10   0
  - b1ba2097-4009-4583-920f-388b11e400b7   0
  - d5550afb-e015-493e-987b-4802a41c5676   0
  - c2e2352c-68f0-4825-9ba3-e4d47561eb62   0
  - 791f7464-3665-403f-8c14-c1348be4c088   0
  - 33035c25-99ab-4460-8535-60deaa8f897e   0
  - 2d045305-5498-4650-9e5d-85de2b06b84f   0
  - 6343e414-59ae-4afd-bc3f-9737b2785a54   0
  - 7ad8699e-784b-464a-8961-b8dc195dd807   0
  - 908d021d-8f12-4eea-a2aa-d509114f2de6   0
  - de1d197c-aa07-4205-a760-7723ae5d2743   0
  - b3b5524a-fc10-4443-97c7-b2aa20f7822f   0
  - bba79552-412d-4b9f-aae1-1fbef16ab623   0
  - 880fe521-dfc1-44ee-ac76-c91bc1181307   0
  - 85ca8e42-adf0-4b41-bc02-590cc3046349   0
  - beb6c6f3-e576-4808-9827-d233547b2b06   0
  - 718cf161-a526-4f92-90af-f7def534420f   0
  - 7313e2ae-313b-4249-8ef4-d14fe06f0061   0
  - 0e010d61-7fcb-4bb3-808d-d76c0f09d4de   0
  - a718a53d-a9df-403d-b702-fee1b2996fe8   0
  - 34cc3355-d69a-4a5b-9bea-d2be78361cd0   0
  - 84b9bc68-545c-453f-b6c4-533df37dbd05   0
  - 1457fcca-8994-460f-a5e1-99bdd63173d8   0
  - 158194d8-a0ca-4290-a8f0-ba4ad8f15b96   0
  - 0c4089cc-47af-4ff1-813c-86f17631d531   0
  - 9429dd44-0dee-4465-925c-724359581a38   0
  - 048cc492-f8c0-4a3e-832d-023aedba0acb   0
  - 386eb625-3a8e-4242-b01e-7f454f91515e   0
  - 1c53dd63-742a-483f-8c9e-8679d03aa7b7   0
  - 2b2cba1a-8d62-41db-9b25-98bc09dc0f97   0
  - ae0d1604-5f12-4181-b403-e19b0fc43823   0
  - 29f555f0-bc2c-459d-9ccb-8778d2e6637f   0
  - c8f4fb3f-f555-4d80-bc11-0ea85cb90303   0
  - ad75a216-ef50-4462-bd31-f618c63b038b   0
  - b0df8902-6fdb-4ae3-9360-92549c469f7f   0
  - 07e275ae-637e-416e-beae-2e67aac386bd   0
  - 4277f2a5-695f-471e-ba3f-533abef33cc6   0
  - eaebec62-17f4-437d-9dcc-d916b2cbd11f   0
  - 71bde842-a272-41f8-bcfe-b8913bcc6a8f   0
  - 76a2fcbf-65fd-4d5e-9c3d-c2c56cee89d5   0
  - fdc828d7-c0b4-4057-b5a5-d3f038761b57   0
  - de2df781-fa4b-49a0-b8e4-956aadca749c   0
  - 0cd21f97-3356-41e1-b7ea-c5c2b153587e   0
  - 9b01e2bf-d4c1-4d46-85ce-206528e8935a   0
  - b0c0f929-c70c-4c0c-9471-562480ca101f   0
  - 4d91d566-1ec4-4048-8107-1df58b2fb5f3   0
  - bd830be2-6021-4554-9c4c-f8e819675877   0
  - 5b88c009-bb27-4a59-8362-a5bbd11cb0ba   0
  - ae297856-6dba-4670-8c87-854356286087   0
  - 4025f8bf-8d7a-4d19-a904-f72e5b8279e8   0
  - 599b98c2-c49e-46a0-b375-e0ae5f3f560b   0
  - 57899d2b-98e0-4698-b060-3eaa81e0ded0   0
  - 7412c7b4-7a6c-4899-b436-bd2b6c6a8680   0
  - f16fdbf6-9b38-4482-bf7c-3df5a090ec51   0
  - 11c795eb-7b5b-4485-8f38-9105af9a0a10   0
  - fcb70153-5281-4d92-9148-9723a8b7ebfd   0
  - 2095b076-da0e-4e1e-af5a-be2c2d51d490   0
  - 272a4a00-3e3a-427a-8902-f547bb212692   0
  - df06c46b-3a59-4823-832d-8809ec55b7ed   0
  - 7acf3bf7-0f55-4443-91ff-453e2ddf865f   0
  - b103e03b-30ed-4843-bf3e-60a548c063ae   0

val:
  - 90c9aead-ba19-4234-8785-a718d8555b05   0
  - 3e248944-5ef9-406b-8a55-2911dc9987be   0
  - d629479a-05b2-4cd9-95de-7ecf90950681   0
  - 470b4c9d-5298-4d4e-aea9-8d8fcf602ef0   0
  - 25234f40-3ab4-4f59-8929-2185c13fa9dd   0

test:
  - e98acca2-38d5-4138-bde1-a509612c0f75   0
  - aa2474bb-7d97-4320-b8ff-1b44893bc523   0
  - b4d5e938-8db3-42e9-9f78-940c20200566   0
  - 42fe3769-d61f-4309-a3fe-cfea81265271   0
  - d26165e1-15d6-454a-a63b-2d044476cf9a   0
  - 89c2a1e8-3f45-4c08-a04d-139b72fbfd53   0
  - cf2a70dc-bf14-44f0-960c-c176d1362215   0
  - b7f78b2c-efec-498f-8a64-8a48fa587514   0
  - 09b74408-b831-40df-8b7b-8b7333a63473   0
  - de8da9e5-0de4-4d7e-a6c9-3288e696d6ce   0
  - 07fc64fb-ac25-4efd-93c9-15fb1f75385b   0
  - e4f8d7af-59c7-425a-afaf-59aa00bb6f48   0
