version: 1
dataset_version: db-tlr-v1.1

train:
  - 8bb655ad-e12e-40a1-a7d7-43f279a1bd51
  - 88320003-580f-466d-9c3d-d0e7177b574b
  - c216afeb-7175-4e96-91b6-cb37e41aec81
  - c05a5248-d758-411b-b699-5852b8af03a9
  - 58f3fa68-acc2-40d6-a232-92c1df584816
  - 287d7dd8-9938-466e-8983-09a0d37736fb
  - 89069d42-b9f4-42c0-b5a0-cd102b310022
  - 8282696f-bae8-4ee1-99d5-b0c6a9ce99fa
  - 78c3d93e-a446-49a6-96ab-eb22ad63ec3f
  - 9401bc38-97db-4190-8da9-6ba2eb097c5c
  - f9cd7804-c5c1-448a-a7da-ab8e6e8064bd
  - 7c4afac7-a9e2-4ee7-bf2a-d9600863eb45
  - 3889534f-a669-48c4-815d-a648089ba1af
  - c2633565-2cef-4944-9161-b5738954650f
  - e757e163-488b-42f3-bd8e-41d001bd6d7b

val: []

test:
  - 470daad9-94f7-47e7-9cb8-4aa1d37e1bb0
  - 0450be6b-9770-4bd1-8c59-649f8e4d9168
